FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

RUN addgroup -S library && adduser -S library -G library

COPY borrow-service/target/*.jar app.jar

RUN chown -R library:library /app

USER library

EXPOSE 8083

ENV JAVA_OPTS="-Xms512m -Xmx1g"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
