bind 0.0.0.0
port 6379

protected-mode no

daemonize no

pidfile /var/run/redis_6379.pid

loglevel notice
logfile ""

databases 16

save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

maxmemory 512mb
maxmemory-policy allkeys-lru

appendonly no
appendfilename "appendonly.aof"
appendfsync everysec

tcp-keepalive 300
timeout 0
tcp-backlog 511
